mutation CreateArgumentVote($argumentVote: ArgumentVoteInput!) {
  createArgumentVote(argumentVote: $argumentVote) {
    argumentVote {
      id
    }

    errors {
      name
      message
    }
  }
}