
mutation UpdatetArgumentVote($argumentVote: ArgumentVoteInput!) {
 	updateArgumentVote(argumentVote: $argumentVote) {
    argumentVote {
      id
    }

    errors {
      name
      message
    }
  }
}