query Statistics($organizationId: ID!, $id: ID!) {
  organization(id: $organizationId) {
    resolution(id: $id) {
      id
      customThreshold
      expireAt
      author {
        id
        user {
          displayName
          pictureThumbUrl
        }
      }
      category {
        id
        name
        threshold {
          id
          value
        }
      }
      votes(all: true) {
        totalCount
        items {
          id
          value
          createdAt
          updatedAt
        }
      }
      members(all: true) {
        totalCount
      }
    }
  }
}
