import Head from "next/head";
import Image from "next/image";
import Menu, { drawerWidth } from "../component/Menu";
import styles from "../styles/Home.module.css";
import { Box, Container, Grid, IconButton } from "@mui/material";
import FormatListBulletedIcon from "@mui/icons-material/FormatListBulleted";
import GridViewIcon from "@mui/icons-material/GridView";
import ListView from "../src/component/Proposals/Home/ListView/listView";
import GridView from "../src/component/Proposals/Home/GridView/gridView";
import resolutions from "../src/component/Proposals/mockDataForTest";
import { useState } from "react";

export default function Home({ ual }) {
  const [view, setView] = useState("listView");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu ual={ual} />
      <Container
        sx={{
          width: { xs: `calc(100% - ${drawerWidth}px)` },
          paddingLeft: { xs: "120px" },
          paddingTop: { xs: "40px" },
        }}
      >
        <Box>
          <IconButton
            color={view === "gridView" ? "primary" : "secondary"}
            aria-label="grid view button"
            component="span"
            sx={{ float: "right" }}
            onClick={() => {setView('gridView')}}
          >
            <GridViewIcon />
          </IconButton>
          <IconButton
            color={view === "listView" ? "primary" : "secondary"}
            aria-label="List view button"
            component="span"
            sx={{ float: "right" }}
            onClick={() => {setView('listView')}}
          >
            <FormatListBulletedIcon />
          </IconButton>
        </Box>
        <Grid
          container
          spacing={0}
          direction="column"
          alignItems="center"
          justify="center"
          sx={{ minHeight: "100vh" }}
        >
          <Grid item md={6} sx={{ width: 1, marginLeft: { xs: "24px" } }}>
            {view === 'listView' && <ListView resolutions={resolutions} />}
            {view === 'gridView' && <GridView resolutions={resolutions} />}
          </Grid>
        </Grid>
      </Container>
    </>
  );
}
